sudo: required
services:
  - docker

before_install:
  - docker build -t thajib/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=TRUE thajib/react-test npm test -- --coverage

after_success:
  - docker build -t thajib/multi-client ./client
  - docker build -t thajib/multi-nginx ./nginx
  - docker build -t thajib/multi-server ./server
  - docker build -t thajib/multi-worker ./worker

  # Login to Docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those images and push them to docker hub
  - docker push thajib/multi-client
  - docker push thajib/multi-nginx
  - docker push thajib/multi-server
  - docker push thajib/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-west-2-940808560637
  bucker_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

