version: '3'
services:

  nginx:
    image: "thajib/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    restart: always
    ports:
      - '8085:80'

  server:
    image: "thajib/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT

  client:
    image: "thajib/multi-client"
    mem_limit: 128m
    hostname: client

  worker:
    image: "thajib/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    
  
  